---
- name: Create resource group
  azure.azcollection.azure_rm_resourcegroup:
    state: "{{ azure_vm_state }}"
    force_delete_nonempty: "{{ azure_vm_state == 'absent' }}"
    name: "{{ azure_vm_resource_group_name }}"
    location: "{{ azure_vm_location }}"

- name: Create virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    state: "{{ azure_vm_state }}"
    resource_group: "{{ azure_vm_resource_group_name }}"
    name: "{{ azure_vm_virtual_network_name }}"
    address_prefixes: "{{ azure_vm_virtual_network_prefixes }}"
  when: azure_vm_state == "present"

- name: Add subnet
  azure.azcollection.azure_rm_subnet:
    state: "{{ azure_vm_state }}"
    resource_group: "{{ azure_vm_resource_group_name }}"
    name: "{{ azure_vm_subnet_name }}"
    address_prefix: "{{ azure_vm_subnet_prefix }}"
    virtual_network: "{{ azure_vm_virtual_network_name }}"
  when: azure_vm_state == "present"

- name: Create public IP address
  azure.azcollection.azure_rm_publicipaddress:
    state: "{{ azure_vm_state }}"
    resource_group: "{{ azure_vm_resource_group_name }}"
    allocation_method: Static
    name: "{{ azure_vm_public_ip_name }}"
  register: azure_vm_output_ip_address
  when: azure_vm_state == "present"

- name: Public IP of VM
  ansible.builtin.debug:
    msg: "The public IP is {{ azure_vm_output_ip_address.state.ip_address }}."
  when: azure_vm_state == "present"

- name: Set fact for public IP
  ansible.builtin.set_fact:
    azure_public_ip_address: "{{ azure_vm_output_ip_address }}"
  when: azure_vm_state == "present"

- name: Create Network Security Group that allows SSH
  azure.azcollection.azure_rm_securitygroup:
    state: "{{ azure_vm_state }}"
    resource_group: "{{ azure_vm_resource_group_name }}"
    name: "{{ azure_vm_nsg_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
  when: azure_vm_state == "present"

- name: Create virtual network interface card
  azure.azcollection.azure_rm_networkinterface:
    state: "{{ azure_vm_state }}"
    resource_group: "{{ azure_vm_resource_group_name }}"
    name: "{{ azure_vm_nic_name }}"
    virtual_network: "{{ azure_vm_virtual_network_name }}"
    subnet_name: "{{ azure_vm_subnet_name }}"
    security_group: "{{ azure_vm_nsg_name }}"
    ip_configurations:
      - name: ipconfig1
        primary: true
        public_ip_address_name: "{{ azure_vm_public_ip_name }}"
  when: azure_vm_state == "present"

- name: Gather public ssh key data
  ansible.builtin.slurp:
    src: "{{ azure_vm_local_ssh_public_key_path }}"
  register: azure_vm_ssh_public_key
  when: azure_vm_state == "present"

- name: Decode Public Key
  ansible.builtin.set_fact:
    azure_vm_public_key_content: "{{ azure_vm_ssh_public_key.content | b64decode }}"
  when: azure_vm_state == "present"

- name: Create VM
  azure.azcollection.azure_rm_virtualmachine:
    state: "{{ azure_vm_state }}"
    resource_group: "{{ azure_vm_resource_group_name }}"
    name: "{{ azure_vm_name }}"
    vm_size: "{{ azure_vm_sku }}"
    admin_username: "{{ azure_vm_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ azure_vm_username }}/.ssh/authorized_keys"
        key_data: "{{ azure_vm_public_key_content }}"
    network_interfaces: "{{ azure_vm_nic_name }}"
    image:
      offer: "0001-com-ubuntu-server-jammy"
      publisher: "Canonical"
      sku: "22_04-lts"
      version: latest
  when: azure_vm_state == "present"
